name: string_collector
version: 0.0.1
description: A simple CLI tool to scan Dart source files and collect string literals into structured JSON files.
repository: https://github.com/4uzhoy/string_collector
issue_tracker: https://github.com/4uzhoy/string_collector/issues
homepage: https://github.com/4uzhoy/string_collector
topics: 
- cli
- strings
- localization
executables:
  string_collector: main.dart

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  path: ^1.9.0
  yaml: ^3.1.2
  meta: any

dev_dependencies:
  lints: ^3.0.0
  test: any
